const getMeta = () => ({
  site: {
    title: 'Shaojiang.io - Frontier of front-end development by Shaojiang Cai',
    robots: 'index, follow',
    description: 'Shaojiang.io provides articles, illustrations, resources, demo code, playground for state-of-art front-end development. The topics cover React, Redux, AngularJS, HTML, CSS, JavaScript, Material-UI, HTTP/HTTPS, OAuth 2.0, TCP, and many more.',
    image: 'https://shaojiang.io/public/images/logo.svg',
    'google:name': 'Shaojiang.io - Frontier of front-end development by Shaojiang Cai',
    'google:description': 'Shaojiang.io provides articles, illustrations, resources, demo code, playground for state-of-art front-end development. The topics cover React, Redux, AngularJS, HTML, CSS, JavaScript, Material-UI, HTTP/HTTPS, OAuth 2.0, TCP, and many more.',
    'google:image': 'https://shaojiang.io/public/images/logo.svg',
    'twitter:card': 'summary',
    'twitter:title': 'Shaojiang.io - Frontier of front-end development by Shaojiang Cai',
    'twitter:description': 'Shaojiang.io provides articles, illustrations, resources, demo code, playground for state-of-art front-end development. The topics cover React, Redux, AngularJS, HTML, CSS, JavaScript, Material-UI, HTTP/HTTPS, OAuth 2.0, TCP, and many more.',
    'twitter:site': '@CoinCheckup',
    'twitter:creator': '@CoinCheckup',
    'twitter:image': 'https://shaojiang.io/images/logo.svg',
    'og:title': 'Shaojiang.io - Frontier of front-end development by Shaojiang Cai',
    'og:description': 'Shaojiang.io provides articles, illustrations, resources, demo code, playground for state-of-art front-end development. The topics cover React, Redux, AngularJS, HTML, CSS, JavaScript, Material-UI, HTTP/HTTPS, OAuth 2.0, TCP, and many more.',
    'og:image': 'https://shaojiang.io/public/images/logo.svg',
    'og:url': 'https://shaojiang.io/',
    'og:site_name': 'Shaojiang.io - Frontier of front-end development by Shaojiang Cai',
    'og:type': 'website',
    'fb:app_id': '1594848230539355',
    'fb:admins': '1477984965629836',
    'p:domain_verify': '076a4febce4e4fe09a77a654b0a03b81',
    '57x57': '/public/images/favicon/apple-icon-57x57.png',
    '60x60': '/public/images/favicon/apple-icon-60x60.png',
    '72x72': '/public/images/favicon/apple-icon-72x72.png',
    '76x76': '/public/images/favicon/apple-icon-76x76.png',
    '114x114': '/public/images/favicon/apple-icon-114x114.png',
    '120x120': '/public/images/favicon/apple-icon-120x120.png',
    '144x144': '/public/images/favicon/apple-icon-144x144.png',
    '152x152': '/public/images/favicon/apple-icon-152x152.png',
    '180x180': '/public/images/favicon/apple-icon-180x180.png',
    '192x192': '/public/images/favicon/android-icon-192x192.png',
    '32x32': '/public/images/favicon/favicon-32x32.png',
    '96x96': '/public/images/favicon/favicon-96x96.png',
    '16x16': '/public/images/favicon/favicon-16x16.png',
  },
});

export default getMeta;
